backend/urls.py
from django.urls import path
from django.conf.urls import url 
from backend import views

app_name = 'backend'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('login-admin/', views.login2_view, name='login2_view'),
    path('logout_view-page/', views.logout_view, name='logout_view'),
    path('password_reset/', views.password_reset_request, name='password_reset_request'),
    path('dashboard-page/', views.dashboard, name='dashboard'),
    path('user_profile-page/', views.user_profile, name='user_profile'),
    path('edit_form-page/', views.edit_form, name='edit_form'),
    path('add_agent-page/', views.add_agent, name='add_agent'),
    path('agent-page/', views.agent, name='agent'),
    path('view_agent-page/<int:agent>', views.view_agent, name='view_agent'),
    path('delete_agent-page/<int:liste_id>', views.delete_agent, name='delete_agent'),
    path('edit_newform-page/', views.edit_newform, name='edit_newform'),
    path('pass_form-page/', views.pass_form, name='pass_form'),
    path('reset/', views.reset, name='reset'),
    path('success-message/', views.success_message, name='success_message'),
    path('register-page/', views.register_form, name='register_form'),
    path('logout/', views.logout_view, name='logout_view'),
    path('view-newlisting/<int:pk>', views.view_newlistingdetails, name='view_newlistingdetails'),
    path('delete-property/<int:listf_id>', views.delete_newproperty, name='delete_newproperty'),
    path('add-newlisting-page/', views.add_newlisting, name='add_newlisting'),
    path('listings-page/', views.new_listings, name='new_listings'),
    path('listings-page/<int:post_id>', views. edit_newlisting, name=' edit_newlisting'),
    path('list-users/', views.list_users, name='list_users'),
    path('list-all-post/', views.list_all_post, name='list_all_post'),
    path('delete_upload/<int:del_id>', views.delete_upload, name='delete_upload'),
    # path('reset-password/',auth_views.PasswordResetView.as_view(template_name='registration/reset-password.html', email_template_name='registration/password-reset-email.html', success_url = reverse_lazy('backend:password_reset_done'), form_class=PasswordReset), name='password_reset'),
    # path('password-reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password-confirm-form.html',form_class=SetPassword, success_url = reverse_lazy('backend:password_reset_complete')), name='password_reset_confirm'),
   
]

estate_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from backend.views import activation_sent_view, activate

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:index_id>/', views.detail_index, name='detail_index'),
    path('pages/', include('frontend.urls')),
    path('backend/', include('backend.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='backend/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='backend/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='backend/password_reset_complete.html'), name='password_reset_complete'),
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from django.conf.urls import url 
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.buy, name='buy'),
    path('detail/<int:buy_id>/', views.detail_buy, name='detail_buy'),
    path('contact-page', views.contact, name='contact'),
    path('contact2/<int:agent_id>/', views.contact2, name='contact2'),
    path('filter-data/', views.filter_data, name='filter_data'),
    path('rent-page', views.rent, name='rent'),
    path('details/<int:rent_id>/', views.detail_rent, name='detail_rent'),
    path('signup-page', views.signup, name='signup'),
    path('user-page', views.user, name='user'),
]

backend/models.py
from django.db import models

# Create your models here.

backend/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core import mail
from django.views.generic import ListView

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView

from django.contrib import messages

 # Password Reset
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

 #  end
from frontend.models import *
from backend.forms import *

# signUp
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from backend.tokens import account_activation_token
from .tokens import account_activation_token
from django.template.loader import render_to_string
#end

# Create your views here.



def password_reset_request(request):
    if request.method == "POST":
        domain = request.headers['Host']
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            # You can use more than one way like this for resetting the password.
            # ...filter(Q(email=data) | Q(username=data))
            # but with this you may need to change the password_reset form as well.
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "backend/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': domain,
                        'site_name':'Real Estate',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'leke.olamide123@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="backend/password_reset.html",
                  context={"password_reset_form": password_reset_form})



@login_required(login_url='/backend/login/')
def dashboard(request):
    if request.user.is_staff:
        return render(request, 'backend/index.html')
    else:
        return render(request, 'backend/user.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return render(request, 'backend/user.html')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'frontend/login.html')

def login2_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Username and Password do not match')
    return render(request, 'frontend/login2.html')


def logout_view(request):
    logout(request)
    return redirect('index')

def success_message(request):
    return render(request, 'backend/success.html')



@login_required(login_url='/backend/login/')
def add_agent(request):
    if request.method == 'POST':
        view_form = AgentForm(request.POST, request.FILES)
        if view_form.is_valid():
            agent = view_form.save(commit=False)
            agent.user = request.user
            agent.save()
            return redirect('backend:add_agent')

    else:
        view_form = AgentForm()
    return render(request, 'backend/add_agent.html', {'agent': view_form})

@login_required(login_url='/backend/login/')
def agent(request):
    agent_list = Agents.objects.filter(user=request.user)
    return render(request, 'backend/agent.html', {'alist':agent_list})


@login_required(login_url='/backend/login/')
def view_agent(request, agent):
    file = get_object_or_404(Agents, pk=agent)
    return render(request, 'backend/view_agent.html', {'post':file})

@login_required(login_url='/backend/login/')
def delete_agent(request, liste_id):
    agent_record = get_object_or_404(Agents, id=liste_id)
    agent_record.delete()
    return redirect('backend:agent')



@login_required(login_url='/backend/login/')
def edit_newlisting(request, post_id):
    single_post = get_object_or_404(AddProperty, id=post_id)
    if request.method == 'POST':
        post_form = EditListing(request.POST, request.FILES, instance=single_post)
        if post_form.is_valid():
            listf = post_form.save(commit=False)
            listf.user = request.user
            listf.save()
            messages.success(request, 'Successfully edited.')

    else:
        post_form = EditListing(instance=single_post)
    return render(request, 'backend/edit_post.html', {'editf': post_form})


@login_required(login_url='/backend/login/')
def new_listings(request):
    hotel_list = AddProperty.objects.filter(user=request.user)
    return render(request, 'backend/newlistings.html', {'hlist':hotel_list})

@login_required(login_url='/backend/login/')
def view_newlistingdetails(request, pk):
    post = get_object_or_404(AddProperty, pk=pk)
    return render(request, 'backend/view-newlisting.html', {'pst':post})

@login_required(login_url='/backend/login/')
def delete_newproperty(request, listf_id):
    post_record = get_object_or_404(AddProperty, id=listf_id)
    post_record.delete()
    return redirect('backend:new_listings')

def register_form(request):
    if request.method  == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.profile.email = form.cleaned_data.get('email')
            # user can't login until link confirmed
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Please Activate Your Account'
            # load a template like get_template()
            # and calls its render() method immediately.
            message = render_to_string('backend/activation_request.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                # method will generate a hash value with user related data
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('activation_sent')

            # messages.success(request, 'User Registered')
    else:
        form = RegisterForm()
    return render(request, 'frontend/signup.html', {'reg':form})

def activation_sent_view(request):
    return render(request, 'backend/activation_sent.html')

def activate (request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # checking if the user exists, if the token is valid.
    if user is not None and account_activation_token.check_token(user, token):
        # if valid set active true
        user.is_active = True
        # set signup_confirmation true
        user.profile.signup_confirmation = True
        user.save()
        login(request, user)
        return redirect('backend:login_view')
    else:
        return render(request, 'backend/activation_invalid.html')


@login_required(login_url='/backend/login/')
def add_newlisting(request):
    if request.method == 'POST':
        list_form = ListingForm(request.POST, request.FILES)
        if list_form.is_valid():
            listf = list_form.save(commit=False)
            listf.user = request.user
            listf.save()
            messages.success(request, 'Add successfully.')
    else:
        list_form = ListingForm()

templates/backend/activation_request.html
{% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/backend/add-newlisting2.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home 
{% endblock %}



<body class="sticky-footer" > 
    {% block content %}
        {% if request.user.is_staff %} 
            {% include 'backend/admin_sidebar.html' %}
        {% else %}
            {% include 'backend/user_sidebar.html' %}
        {% endif %}
            
    
        <div class="content-wrapper">
            <div class="container-fluid">
                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                    <a href="{%url 'index' %}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item active">Add listing</li>
                </ol>
                    <div class="box_general padding_bottom">
                        <div class="header_box version_2">
                            <h2><i class="fa fa-file"></i>Basic info</h2>
                        </div>
                        <div class="row">
                            <form method="post" enctype="multipart/form-data">
                                {{ lista.as_p }}
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Save</button>
                            </form>
    
                        
                    </div>
                    <!-- /box_general-->
                    
            </div>
            <!-- /.container-fluid-->
        </div>
        <!-- /.container-wrapper-->
    
    {% endblock %}



    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            </div>
            <div class="modal-body">{{ request.user.get_full_name }}Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'backend:logout_view' %}">Logout</a>
            </div>
        </div>
        </div>
    </div>


  <script src="{% static 'backend/vendor/chart.js/Chart.js' %}"></script>
  <script src="{% static 'backend/js/admin-charts.js' %}"></script>

templates/backend/admin_sidebar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-default fixed-top" id="mainNav" style="font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
    <a class="navbar-brand" href="{%url 'index' %}" style="height: 36px; width: 150px;">REAL ESTATE</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <a class="text-warning">
      <span class="float-right name" style="text-transform: capitalize;">Welcome as Admin, {{ request.user.get_full_name }}</span>
    </a> -->
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <h4 class="text-success">
          <span style=" font-weight: 800; margin-left: 30px; font-size: 25px; text-transform: capitalize;
          color:red; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"><a href="{% url 'backend:dashboard' %}">{{ request.user.get_username }}</a></span>
          </h4>
          <hr>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{%url 'backend:dashboard' %}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
          <a class="nav-link" href="{%url 'backend:add_newlisting' %}">
            <i class="fa fa-fw fa-plus-circle"></i>
            <span class="nav-link-text">Add Property</span>
          </a>
        </li>
        <li class="nav-item"  data-toggle="tooltip" data-placement="right" title="View Properties">
          <a class="nav-link"  href="{%url 'backend:new_listings'%}" >
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">My Property</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
          <a class="nav-link" href="{%url 'backend:add_agent' %}">
            <i class="fa fa-fw fa-plus-circle"></i>
            <span class="nav-link-text">Add Agent</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
          <a class="nav-link" href="{%url 'backend:agent' %}">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">View Agent</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
          <a class="nav-link" href="{%url 'backend:list_all_post' %}">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">View All Post</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
          <a class="nav-link" href="{%url 'backend:list_users' %}">
            <i class="fa fa-fw fa-user-circle"></i>
            <span class="nav-link-text">View Users</span>
          </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My profile">
          <a class="nav-link" href="{% url 'backend:user_profile' %}">
            <i class="fa fa-fw fa-user"></i>
            <span class="nav-link-text">My Profile</span>
          </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Edit profile">
      <a class="nav-link" href="{%url 'backend:edit_newform' %}">
        <i class="fa fa-fw fa-user"></i>
      <span href="#">Edit Profile </span>
      </a>
    </li>
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Change Password">
      <a class="nav-link" href="{%url 'backend:pass_form' %}">
        <i class="fa fa-fw fa fa-lock"></i>
        <span class="nav-link-text">Change Password</span>
      </a>
    </li>
      </ul>

      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'frontend:buy' %}">Buy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'frontend:rent' %}">Rent</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'frontend:contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
        
      </ul> 
      
    </div>
</nav>

templates/backend/agent.html
{% extends 'backend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home 
{% endblock %}



{% block content %}
<body class="fixed-nav sticky-footer" id="page-top">
    {% if request.user.is_staff %}
        {% include 'backend/admin_sidebar.html' %}
    {% else %}
        {% include 'backend/user_sidebar.html' %}
    {% endif %}
    <div class="container-fluid">
        <div class="row">
            
            <section class="col-md-12">
                <div class="content-wrapper">
                    <div class="container-fluid">
                      <!-- Breadcrumbs-->
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                          <a href="{%url 'index' %}">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">View Property</li>
                      </ol>
                        <div class="box_general">
                            <div class="header_box">
                                <h2 class="d-inline-block" style="color: #1ec5cb !important;">View Agents</h2>
                                <div class="filter">
                                    <select name="orderby" class="selectbox">
                                        <option value="Any time">Any time</option>
                                        <option value="Latest">Latest</option>
                                        <option value="Oldest">Oldest</option>     
                                    </select>
                                </div>
                            </div>
                            <div class="list_general" style="font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
                                <ul>
                                    <li>
                                        {% if alist %}
                                            {% for h in alist %}
                                                <figure><img src="{{ h.agent_img.url }}" alt="" ></figure>
                                                <small>Agents</small>
                                                <h4>{{ h.agent_title }}</h4>
                                                <p>{{ h.agent_desription|truncatewords:50 }}</p>
                                                <div class="row">
                                                    <p class=" col-md-4"><a href="{% url 'backend:view_agent' h.id %}" class="btn_1 gray"><i class="fa fa-fw fa-eye"></i> View Details</a></p>
                                                    <p class=" col-md-4"><a href="{% url 'backend:delete_agent' h.id %}"  class="btn_1 gray delete wishlist_close"><i class="fa fa-fw fa-times-circle-o"></i> Delete</a></p>     
                                                </div>  
                                            {% endfor %}
                                        {% endif %}
                                    </li>
                                </ul>       
                            </div>
                        </div>
                    </div>
                </div>
            </section>
                <!-- /.container-wrapper-->
                
        </div>
    </div>



    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            </div>
            <div class="modal-body">{{ request.user.get_full_name }}Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'backend:logout_view' %}">Logout</a>
            </div>
        </div>
        </div>
    </div>


  <script src="{% static 'backend/vendor/chart.js/Chart.js' %}"></script>
  <script src="{% static 'backend/js/admin-charts.js' %}"></script>
</body>
{% endblock %}

templates/backend/user_sidebar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-default fixed-top" id="mainNav" style="font-family: Georgia, 'Times New Roman', Times, serif; font-style: oblique;">
  <a class="navbar-brand" href="{% url 'index' %}"><h3>Real Estate</h3></a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <a class="nav-link" href="{% url 'backend:dashboard' %}">
          <h4 class="text-success">
            <span style=" font-weight: 800; margin-left: 30px; font-size: 25px; text-transform: capitalize;
            color:rgb(0, 17, 255); font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">{{ request.user.get_username }}</span>
            </h4>
            <hr>
          <i class="fa fa-fw fa-dashboard"></i>
          <span class="nav-link-text">Dashboard</span>
        </a>
      </li>
      <li class="nav-item"  data-toggle="tooltip" data-placement="right" title="View Properties">
        <a class="nav-link"  href="{%url 'backend:new_listings'%}" >
          <i class="fa fa-fw fa-list"></i>
          <span class="nav-link-text">View Property</span>
        </a>
      </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
        <a class="nav-link" href="{%url 'backend:add_newlisting' %}">
          <i class="fa fa-fw fa-plus-circle"></i>
          <span class="nav-link-text">Add Property</span>
        </a>
      </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="My profile">
        <a class="nav-link" href="{% url 'backend:user_profile' %}">
          <i class="fa fa-fw fa-user"></i>
          <span class="nav-link-text">My Profile</span>
        </a>
  </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Edit profile">
    <a class="nav-link" href="{%url 'backend:edit_newform' %}">
      <i class="fa fa-fw fa-user"></i>
    <span href="#">Edit Profile </span>
    </a>
  </li>
  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Change Password">
    <a class="nav-link" href="{%url 'backend:pass_form' %}">
      <i class="fa fa-fw fa fa-lock"></i>
      <span class="nav-link-text">Change Password</span>
    </a>
  </li>
</ul>
  <ul class="navbar-nav sidenav-toggler">
    <li class="nav-item">
      <a class="nav-link text-center" id="sidenavToggler">
        <i class="fa fa-fw fa-angle-left"></i>
      </a>
    </li>
  </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item" style="margin-right: 30px; font-size: 22px; ">
          <a href="{%url 'backend:dashboard' %}">Welcome {{ request.user.get_username }} </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'frontend:buy' %}">Buy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'frontend:rent' %}">Rent</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'frontend:contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
        
      </ul> 
    </ul>
  </div>
</nav>