backend/urls.py
from django.urls import path
from django.conf.urls import url 
from backend import views

app_name = 'backend'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('login-admin/', views.login2_view, name='login2_view'),
    path('logout_view-page/', views.logout_view, name='logout_view'),
    path('password_reset/', views.password_reset_request, name='password_reset_request'),
    path('dashboard-page/', views.dashboard, name='dashboard'),
    path('user_profile-page/', views.user_profile, name='user_profile'),
    path('edit_form-page/', views.edit_form, name='edit_form'),
    path('add_agent-page/', views.add_agent, name='add_agent'),
    path('agent-page/', views.agent, name='agent'),
    path('view_agent-page/<int:agent>', views.view_agent, name='view_agent'),
    path('delete_agent-page/<int:liste_id>', views.delete_agent, name='delete_agent'),
    path('edit_newform-page/', views.edit_newform, name='edit_newform'),
    path('pass_form-page/', views.pass_form, name='pass_form'),
    path('reset/', views.reset, name='reset'),
    path('success-message/', views.success_message, name='success_message'),
    path('register-page/', views.register_form, name='register_form'),
    path('logout/', views.logout_view, name='logout_view'),
    path('view-newlisting/<int:pk>', views.view_newlistingdetails, name='view_newlistingdetails'),
    path('delete-property/<int:listf_id>', views.delete_newproperty, name='delete_newproperty'),
    path('add-newlisting-page/', views.add_newlisting, name='add_newlisting'),
    path('listings-page/', views.new_listings, name='new_listings'),
    path('listings-page/<int:post_id>', views. edit_newlisting, name=' edit_newlisting'),
    path('list-users/', views.list_users, name='list_users'),
    path('list-all-post/', views.list_all_post, name='list_all_post'),
    path('delete_upload/<int:del_id>', views.delete_upload, name='delete_upload'),
    # path('reset-password/',auth_views.PasswordResetView.as_view(template_name='registration/reset-password.html', email_template_name='registration/password-reset-email.html', success_url = reverse_lazy('backend:password_reset_done'), form_class=PasswordReset), name='password_reset'),
    # path('password-reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password-confirm-form.html',form_class=SetPassword, success_url = reverse_lazy('backend:password_reset_complete')), name='password_reset_confirm'),
   
]

estate_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from frontend import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from backend.views import activation_sent_view, activate

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:index_id>/', views.detail_index, name='detail_index'),
    path('pages/', include('frontend.urls')),
    path('backend/', include('backend.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='backend/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='backend/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='backend/password_reset_complete.html'), name='password_reset_complete'),
    path('sent/', activation_sent_view, name="activation_sent"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path
from django.conf.urls import url 
from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.buy, name='buy'),
    path('detail/<int:buy_id>/', views.detail_buy, name='detail_buy'),
    path('contact-page', views.contact, name='contact'),
    path('contact2/<int:agent_id>/', views.contact2, name='contact2'),
    path('filter-data/', views.filter_data, name='filter_data'),
    path('rent-page', views.rent, name='rent'),
    path('details/<int:rent_id>/', views.detail_rent, name='detail_rent'),
    path('signup-page', views.signup, name='signup'),
    path('user-page', views.user, name='user'),
]

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.


class Agents(models.Model):
    agent_img = models.ImageField(blank=True, verbose_name='Profile Image', null=True, upload_to='uploads/', default='')
    agent_title = models.CharField(max_length=100, verbose_name='Profile Title')
    agent_desription = models.TextField(verbose_name='Description')
    agent_contact = models.CharField(max_length=20, verbose_name='Contact')
    agent_address = models.CharField(max_length=100, verbose_name='Address')
    agent_email = models.EmailField(max_length=50, verbose_name='Email')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta():
        verbose_name_plural = 'Agents'


    def __str__(self):
        return self.agent_title




class AddProperty(models.Model):
    BUY = "B"
    RENT = "R"
    CHOOSE = ""

    OFFER_TYPE = [
        (BUY, 'Buy'),
        (RENT, 'Rent'),
        (CHOOSE, 'Please Choose')

    ]


    BUNGALOW = "Bungalow"
    DUPLEX = "Duplex"
    FLAT = "Flat"
    GLASSHOUSE = "Glasshouse"
    STORY_BUILDING = "Story Building"
    CHOOSE = ""

    PROPERTY_TYPE = [

        (BUNGALOW, 'Bungalow'),
        (DUPLEX, 'Duplex'),
        (FLAT, 'Flat'),
        (GLASSHOUSE, 'Glass House'),
        (STORY_BUILDING, 'Story Building'),
        (CHOOSE, 'Please Choose')

    ]


    ONE = "100,000"
    TWO = "150,00"
    THREE = "200,000"
    FOUR = "250,000"
    FIVE = "300,000"
    SIX = "350,000"
    SEVEN = "400,000"
    EIGHT = "450,000"
    NINE = "500,000"
    TEN = "550,000"
    ONE1 = "600,000"
    TWO2 = "650,000"
    THREE3 = "700,000"
    FOUR4 = "750,000"
    FIVE5 = "800,000"
    SIX6 = "850,000"
    SEVEN7 = "900,000"
    EIGHT8 = "950,000"
    NINE9 = "1 Million"
    TEN10 = "1.5 Million"
    ONE11 = "2 Million"
    TWO22 = "2.5 Million"
    THREE33 = "3 Million"
    FOUR44 = "3.5 Million"
    FIVE55 = "4 Million"
    SIX66 = "4.5 Million"
    SEVEN77= "5 Million"
    CHOOSE = ""

    PRICE= [
         (ONE, ' 100,000'),
         (TWO, ' 150,000'),
         (THREE, ' 200,000'),
         (FOUR, ' 250,000'),
         (FIVE, ' 300,000'),
         (SIX, ' 350,000'),
         (SEVEN, ' 400,000'),
         (EIGHT, ' 450,000'),
         (NINE, ' 500,000'),
         (TEN, ' 550,000'),
         (ONE1, ' 600,000'),
         (TWO2, ' 650,000'),
         (THREE3, ' 700,000'),
         (FOUR4, ' 750,000'),
         (FIVE5, ' 800,000'),
         (SIX6, ' 850,000'),
         (SEVEN7, ' 900,000'),
         (EIGHT8, ' 950,000'),
         (NINE9, ' 1 Million'),
         (TEN10, ' 1.5 Million'),
         (ONE11, ' 2 Million'),
         (TWO22, ' 2.5 Million'),
         (THREE33, ' 3 Million'),
         (FOUR44, ' 3.5 Million'),
         (FIVE55, ' 4 Million'),
         (SIX66, ' 4.5 Million'),
         (SEVEN77, ' 5 Million'),
         (CHOOSE, 'Please Choose')
    ]
    add_img = models.ImageField(blank=True, verbose_name='Property image', null=True, upload_to='uploads/' )
    img1 = models.ImageField(blank=True, verbose_name='Other Images', null=True, upload_to='uploads/' )
    img2 = models.ImageField(blank=True, verbose_name='Other Images', null=True, upload_to='uploads/' )
    img3 = models.ImageField(blank=True, verbose_name='Other Images', null=True, upload_to='uploads/' )
    add_title = models.CharField(max_length=100, verbose_name='Property Name')
    add_price = models.CharField(max_length=40, choices=PRICE, default=CHOOSE)
    listing_type = models.CharField(max_length=40, choices=PROPERTY_TYPE, default=CHOOSE)
    add_desription = models.TextField(verbose_name='Description')
    add_contact = models.CharField(max_length=20, verbose_name='Contact')
    add_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    offer_type = models.CharField(max_length=40, choices=OFFER_TYPE, default=CHOOSE)
    sponsored =models.BooleanField()
    featured = models.BooleanField()


    class Meta():
        verbose_name_plural = 'AddProperty'

    def __str__(self):
        return self.add_title

    def img_url(self):
        if self.add_img:
            return self.add_img.url

    def img1_url(self):
        if self.img1:
            return self.img1.url

    def img2_url(self):
        if self.img2:
            return self.img2.url

    def img3_url(self):
        if self.img3:
            return self.img3.url




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)
    signup_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    try:
        instance.profile.save()
    except ObjectDoesNotExist:
        Profile.objects.create(user=instance)

frontend/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from frontend.models import *
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from backend.forms import *

# for sending mail import
from django.conf import settings
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

 # Password Reset
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

 #  end

from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def index(request):
    profile =AddProperty.objects.order_by('-add_date')[:3]
    featured=AddProperty.objects.all().filter(featured=True)[:3]
    sponsored=AddProperty.objects.all().filter(sponsored=True)[:3]
    profile2 =Agents.objects.all()[:3]
    query_form = FilterForm()
    files = {'pro':profile,'featured':featured, 'sponsored':sponsored, 'agent':profile2, 'qf':query_form }
    return render(request, 'frontend/index.html', files)

def detail_index(request, index_id):
    detail =AddProperty.objects.get(id=index_id)
    return render(request, 'frontend/detail.html', {'detail1':detail})


def filter_data(request):
    if request.method == 'GET':
        query_form = FilterForm(request.GET)
        if query_form.is_valid():
            print('Correct')
            add_price = query_form.cleaned_data.get('add_price')
            offer_type = query_form.cleaned_data.get('offer_type')
            listing_type = query_form.cleaned_data.get('listing_type')
            post = AddProperty.objects.all()
            query = AddProperty.objects.filter(offer_type=offer_type,add_price=add_price, listing_type=listing_type)
            return render(request, 'frontend/filter.html', {'q': query})
        else:
            print('Not found')
            return render(request, 'frontend/filter2.html')
    # else:
    #     query_form = FilterForm()
    # return render(request, 'frontend/filter2.html')

def buy(request):
    # sale = AddProperty.objects.all()
    most_recent = AddProperty.objects.order_by('-add_date')
    add_post = AddProperty.objects.order_by('-add_date')
    paginated_filter = Paginator(add_post,6)
    page_number = request.GET.get('page')
    person_page_obj = paginated_filter.get_page(page_number)
    context = {
        'person_page_obj': add_post,
        'most_recent': most_recent
        # 'buy':sale
    }
    context['person_page_obj'] = person_page_obj
    if request.method == 'POST':
        email = request.POST["email"]
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
    return render(request, 'frontend/buy.html', context)

def detail_buy(request, buy_id):
    detail =AddProperty.objects.get(id=buy_id)
    agent_email = detail.user.email
    if request.method =='POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(name+' '+email+' '+message)
        subject = 'Client Form'
        context = {'name':name, 'email':email, 'message':message }
        html_message =render_to_string('frontend/mail-template2.html', context)
        plain_message = strip_tags(html_message)
        from_email = 'Client <leke.olamide123@gmail.com>'
        send =  mail.send_mail(subject, plain_message, from_email, [agent_email], html_message=html_message, fail_silently=True)
        if send:
            messages.success(request, 'Email sent sucessfully')
        else:
            messages.error(request, 'Mail not sent')
    return render(request, 'frontend/detail.html', {'det':detail})

def contact(request):
    if request.method =='POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(name+' '+email+' '+message)
        subject = 'Contact Us Form'
        context = {'name':name, 'email':email, 'message':message }
        html_message =render_to_string('frontend/mail-template.html', context)
        plain_message = strip_tags(html_message)
        from_email = 'From <leke.olamide123@gmail.com>'
        send =  mail.send_mail(subject, plain_message, from_email, ['leke.olamide123@gmail.com'], html_message=html_message, fail_silently=True)
        if send:
            messages.success(request, 'Email sent sucessfully')
        else:
            messages.error(request, 'Mail not sent')

    return render(request, 'frontend/contact.html')

def contact2(request, agent_id):
    contact =Agents.objects.get(id=agent_id)
    return render(request, 'frontend/contact2.html', {'con':contact})

def rent(request):
    # hire = AddProperty.objects.all()
    most_recent = AddProperty.objects.order_by('-add_date')
    add_post = AddProperty.objects.order_by('-add_date')
    paginated_filter = Paginator(add_post,6)
    page_number = request.GET.get('page')
    person_page_obj = paginated_filter.get_page(page_number)
    context = {
        'person_page_obj': add_post,
        'most_recent': most_recent
        # 'rent':hire
    }
    context['person_page_obj'] = person_page_obj
    if request.method == 'POST':
        email = request.POST["email"]
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
    return render(request, 'frontend/rent.html', context)

def detail_rent(request, rent_id):
    detail2 =AddProperty.objects.get(id=rent_id)
    if request.method =='POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(name+' '+email+' '+message)
        subject = 'Client Form'
        context = {'name':name, 'email':email, 'message':message }
        html_message =render_to_string('frontend/mail-template2.html', context)
        plain_message = strip_tags(html_message)
        from_email = 'Client <leke.olamide123@gmail.com>'
        send =  mail.send_mail(subject, plain_message, from_email, ['leke.olamide123@gmail.com', email], html_message=html_message, fail_silently=True)
        if send:
            messages.success(request, 'Email sent sucessfully')
        else:
            messages.error(request, 'Mail not sent')
    return render(request, 'frontend/detail.html', {'detail':detail2})

def signup(request):
    return render(request, 'frontend/signup.html')

def user(request):
    return render(request, 'frontend/user.html')

templates/frontend/contact2.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home
{% endblock %}
<body>


	<div id="fh5co-page">
	{% block content %}

		<div class="fh5co-page-title" style="background-image: url({% static 'frontend/images/home.jpg' %});">
			<div class="overlay"></div>
			<div class="container">
				<div class="row">
					<div class="col-md-12 animate-box">
						<h1 style="color: #ffff !important;"><span class="colored">Contact</span> Agent</h1>
					</div>
				</div>
			</div>
		</div>


		<div class="fh5co-contact animate-box">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						<h3 style="font-size:32px; color: cadetblue !important;">Agent Info.</h3>
						<h1 style="font-size: 30px;">{{ con.agent_title }}</h1>
						<ul class="contact-info">
							<li><i class="fa fa-map"></i>{{ con.agent_address }}</li>
							<li><i class="fa fa-phone"></i>{{ con.agent_contact }}</li>
							<li><i class="fa fa-envelope"></i><a href="#">{{ con.agent_email }}</a></li>
						</ul>
					</div>
			        <form class="col-md-6 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0" method='POST'>
						<div class="row">
						<figure>
							<img class=" img-responsive col-sm-12" src="{{con.agent_img.url }}" style="width:400px; height:200;">
						</figure>
						</div>
					</form>
				</div>
			</div>
		</div>

	{% endblock %}
</body>

templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home
{% endblock %}
<body>
	{% block content %}
	
	<div id="fh5co-page">
		
		<aside id="fh5co-hero" clsas="js-fullheight" style="background-image: url({% static 'frontend/images/home.jpg' %}); background-repeat: no-repeat; background-size: cover;">
				<div class="container">
				  <div class="row">
					  <div class="col">
						<form method="GET" class="form-inline" style="margin-top: -100px; padding-top: 300px; margin-left:40px" action="{% url 'frontend:filter_data'%}" >
							<div class="row col-lg-12" style="background-color:#bbbb; opacity:0.1px; padding-top:50px; padding-bottom: 50px;">
								<div class="form-group col-sm-10 col-lg-3">
									{{ qf.listing_type }}
								</div>
								<div class="form-group col-sm-10 col-lg-3">
									{{ qf.offer_type }}
								</div>
								<div class="form-group col-sm-10 col-lg-3">
									{{ qf.add_price }}
								</div>
								<div class="col-md-3 col-sm-10 col-lg-3 style=" border-radius: 20px; padding-top:10px;">
									<input type="submit" class="btn btn-primary" value="Filter">
								</div>
							</div>
							
						</form>
					</div>
					
				  </div>  
				 
				</div>
			
		</aside>

		<div id="best-deal">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-md-offset-2 text-center fh5co-heading animate-box" data-animate-effect="fadeIn">
						<h2>We are Offering the Best Real Estate Deals</h2>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
					</div>
					{% if sponsored %}
						{% for p in sponsored %}
							<div class="col-md-4 item-block animate-box" data-animate-effect="fadeIn" style="min-height: 200px;">
								<div class="fh5co-property" style="min-height: 200px;">
									<figure>
										<a href="{% url 'frontend:detail_buy' p.id %}"><img src="{{ p.img_url }}" alt="Free Website Templates FreeHTML5.co" class="img-responsive col-lg-12"></a>
										<a href="{% url 'frontend:detail_buy' p.id %}" class="tag">{{p.pro_sale }}</a>
									</figure>
									<div class="fh5co-property-innter">
										<h3><a href="{% url 'frontend:detail_buy' p.id %}">{{p.add_title }}</a></h3>
										<div class="price-status">
										<span class="price">&#8358;{{p.add_price }} </span>
									</div>
									<p>{{p.add_desription|truncatewords:40 }}</p>
									<p>Contact Us:&nbsp; {{ p.add_contact }}</p>
									</div>
									<p class="fh5co-property-specification">
										{{p.add_date }}
									</p>
								</div>

								
							</div>
						{% endfor%}
					{% endif %}

				</div>
			</div>
			<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h1 class='text-center'>latest Properties</h1>
				</div>
				{% if pro %}
					{% for p in pro %}
					<div class="col-md-4 item-block animate-box" data-animate-effect="fadeIn" style="min-height: 200px;">
						<div class="fh5co-property" style="min-height: 200px;">
							<figure>
								<a href="{% url 'frontend:detail_buy' p.id %}"><img src="{{ p.img_url }}" alt="Free Website Templates FreeHTML5.co" class="img-responsive col-lg-12"></a>
								<a href="{% url 'frontend:detail_buy' p.id %}" class="tag">{{p.pro_sale }}</a>
							</figure>
							<div class="fh5co-property-innter">
								<h3><a href="{% url 'frontend:detail_buy' p.id %}">{{p.add_title }}</a></h3>
								<div class="price-status">
								<span class="price">&#8358;{{p.add_price }} </span>
							</div>
							<p>{{p.add_desription|truncatewords:40 }}</p>
							<p>Contact Us:&nbsp; {{ p.add_contact }}</p>
							</div>
							<p class="fh5co-property-specification">
								{{p.add_date }}
							</p>
						</div>

						
					</div>
					{% endfor%}
				{% endif %}
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h1 class='text-center '>Featured Properties</h1>
				</div>
				{% if featured %}
					{% for f in featured %}
						<div class="col-md-4 item-block animate-box" data-animate-effect="fadeIn" style="min-height: 200px;">
							<div class="fh5co-property" style="min-height: 200px;">
								<figure>
									<a href="{% url 'frontend:detail_buy' f.id %}"><img src="{{ f.img_url }}" alt="Free Website Templates FreeHTML5.co" class="img-responsive col-lg-12"></a>
									<a href="{% url 'frontend:detail_buy' f.id %}" class="tag">{{f.pro_sale }}</a>
								</figure>
								<div class="fh5co-property-innter">
									<h3><a href="{% url 'frontend:detail_buy' f.id %}">{{f.add_title }}</a></h3>
									<div class="price-status">
									<span class="price">&#8358;{{f.add_price }} </span>
								</div>
								<p>{{f.add_desription|truncatewords:40 }}</p>
								<p>Contact Us:&nbsp; {{ f.add_contact }}</p>
								</div>
								<p class="fh5co-property-specification">
									{{f.add_date }}
								</p>
							</div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
		</div>

		<div id="fh5co-testimonial">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-md-offset-2 text-center fh5co-heading animate-box" data-animate-effect="fadeIn">
						<h2>Happy Clients</h2>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
					</div>
					<div class="col-md-4 text-center item-block animate-box" data-animate-effect="fadeIn">
						<blockquote>
							<p>&ldquo; She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of. &rdquo;</p>
							<p><span class="fh5co-author"><cite>Oluwagbemileke</cite></span><i class="fa twitter-color fa-twitter pull-right"></i></p>

						</blockquote>
					</div>
					<div class="col-md-4 text-center item-block animate-box" data-animate-effect="fadeIn">
						<blockquote>
							<p>&ldquo; Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way. She had a last view back on the skyline of her hometown Bookmarksgrove, the headline of. &rdquo;</p>
							<p><span class="fh5co-author"><cite>Leke Olamide</cite></span><i class="fa googleplus-color fa-google-plus pull-right"></i></p>
						</blockquote>
					</div>
					<div class="col-md-4 text-center item-block animate-box" data-animate-effect="fadeIn">
							
						<blockquote>
							<p>&ldquo; The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. S	he had a last view back on the skyline of her hometown Bookmarksgrove. &rdquo;</p>
							<p><span class="fh5co-author"><cite>Mit Chell</cite></span><i class="fa facebook-color fa-facebook pull-right"></i></p>
						</blockquote>
					</div>
				</div>
			</div>
		</div>

		<div id="fh5co-agents" style="background-color: black;">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-md-offset-2 text-center fh5co-heading animate-box" data-animate-effect="fadeIn">
						<h2 style="color:#ffff !important;">Our Trusted Agents</h2>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
					</div>
					{% if agent %}
						{% for a in agent %}
							<div class="col-md-4 text-center item-block animate-box" data-animate-effect="fadeIn" style="min-height: 200px;">
								<div class="fh5co-agent">
									<figure>
										<img src="{{ a.agent_img.url }}">
									</figure>
									<h1 style="font-size: 30px;">{{ a.agent_title }}</h1>
									<p>{{ a.agent_desription }}</p>
									<p><a href="{% url 'frontend:contact2' a.id %}" class="btn btn-primary btn-outline">Contact</a></p>
								</div>								
							</div>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	{% endblock %}
</body>
</html>


templates/frontend/login.html
{% extends 'frontend/base.html' %}
{% load static %}
<!DOCTYPE html>

{% block title%}
Home
{% endblock %}

  <body>
    {% block content %}
      <div class="container-fluid js-fullheight" style="background-image: url({% static 'frontend/images/bg-6.jpg' %}); background-repeat: no-repeat; background-size: cover;" >
        <div class="row">
          <div class="col-sm-4 col-sm-offset-4 pb-5" style="margin-top:60px;">
            <div class="login-form bg-primary" style="border-radius:10px; padding: 20px; border-radius: 10px;">
              <div class="text-center" >
                <h1 style="font-family: monospace;">Login</h1>
              </div>
              <form method='post' action="" class="form">
                {% if messages %}
                  {% for mes in messages %}
                    <div class="alert {{ mes.tags }}">{{ mes }}</div>
                  {% endfor %}
                {% endif %}
                <div class="form-group">
                  <label>Username</label>
                  <input type="text" name="username" placeholder="Username" class="form-control" style="border-radius:10px; background-color:#ffff !important;">
                  <!-- <i class="ti-user"></i> -->
                </div>
                <div class="form-group">
                  <label>Password</label>
                  <input type="password" name="password" placeholder="Password" class="form-control" style="border-radius:10px; background-color:#ffff !important;">
                  <!-- <i class="icon-lock-alt"></i> -->
                </div>
                <div class="pt-3">
                  <input type="submit" name="login" value="Login" class="btn btn-success btn-block ">
                </div>

                <div class="row" style="font-size:14px !important;">
                  <div class="col-sm-4 mt-5 col-4">
                    <h5><a href="{%url 'backend:password_reset_request' %}"  class="login-links" style="color: black;font-size:14px !important;">Reset Password</a></h5>
                  </div>
                  <div class="col-sm-4 mt-5 col-4">
                    <h5><a href="{% url 'index' %}" class="login-links icon-home" style="color: black;font-size:14px !important; margin-left: 30px;">&nbsp;Home</a></h5>
                  </div>
                  <div class="col-sm-4 mt-5 col-4 pt-1">
                    <h5><a href="{%url 'backend:register_form' %}" class="login-links pull-right icon-user" style="color: black;font-size:14px !important;">&nbsp;Sign Up</a></h5>
                  </div>
                </div>
                {% csrf_token %}
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endblock %}
	</body>